### ISSUE TITLE
Minimap flickers sometimes in modular scene

### ISSUE THREAD

**Issue by Ronan-H** [DylanLoftus/APPLIED-PROJECT-AND-MINOR-DISSERTATION#15]
Minimap seems to flicker between the player's view and the minimap view in the modular scene.

Seems to happen only when the player adds >=2 additional rooms and walks past the first set of doors in the hallway.

**Comment by DylanLoftus** [comment]
Changed the Update() method to a LateUpdate() method so that the camera isn't constantly trying to readjust AS the player moves.
